# Generated by Django 5.2.14 on 2026-05-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codice progetto')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile')),
            ],
            options={
                'verbose_name': 'Cartella progetto',
                'verbose_name_plural': 'Cartelle progetto',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_code', models.CharField(max_length=20, verbose_name='Codice revisione')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('ISSUED', 'Emessa'), ('SUPERSEDED', 'Superata')], default='DRAFT', max_length=20, verbose_name='Stato')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_project_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Autore')),
                ('project_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.projectfolder', verbose_name='Progetto')),
            ],
            options={
                'verbose_name': 'Revisione progetto',
                'verbose_name_plural': 'Revisioni progetto',
                'ordering': ['project_folder', '-created_at'],
                'unique_together': {('project_folder', 'revision_code')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveSmallIntegerField(verbose_name='Numero voce')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revision_items', to='documents.documentversion', verbose_name='Revisione documento collegata')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.projectrevision', verbose_name='Revisione progetto')),
            ],
            options={
                'verbose_name': 'Voce revisione progetto',
                'verbose_name_plural': 'Voci revisione progetto',
                'ordering': ['revision', 'item_number'],
                'unique_together': {('revision', 'item_number')},
            },
        ),
    ]
