# Generated by Django 5.2.14 on 2026-05-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectfoldermembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrevision',
            options={'ordering': ['project_folder', '-created_at'], 'verbose_name': 'Revisione cartella', 'verbose_name_plural': 'Revisioni cartella'},
        ),
        migrations.AlterModelOptions(
            name='projectrevisionitem',
            options={'ordering': ['revision', 'item_number'], 'verbose_name': 'Voce revisione cartella', 'verbose_name_plural': 'Voci revisione cartella'},
        ),
        migrations.AlterField(
            model_name='projectfolder',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codice'),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='project_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.projectfolder', verbose_name='Cartella'),
        ),
        migrations.AlterField(
            model_name='projectrevisionitem',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.projectrevision', verbose_name='Revisione cartella'),
        ),
    ]
