# Generated by Django 5.2.14 on 2026-06-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectrevision_rebase_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfolder',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=1000, verbose_name='Path materializzato'),
        ),
    ]
