# Generated by Django 5.2.14 on 2026-06-03 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0008_projectfolder_path_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(choices=[('read_published', 'Leggi documenti pubblicati'), ('view_history', 'Vedi storico versioni'), ('view_obsolete_documents', 'Vedi documenti obsoleti'), ('view_projects', 'Vedi progetti nella cartella'), ('view_folder_ecns', 'Vedi ECN della cartella'), ('create_draft', 'Crea bozze'), ('submit_for_approval', 'Invia in approvazione'), ('eligible_document_approver', 'Eleggibile come approvatore'), ('manage_rejected_drafts', 'Gestisci bozze rifiutate'), ('manage_project_documents', 'Gestisci documenti progetto'), ('request_ecn', 'Richiedi variante ECN'), ('manage_folder', 'Gestisci cartella')], max_length=60, verbose_name='Permesso')),
                ('effect', models.CharField(choices=[('allow', 'Consenti'), ('deny', 'Nega')], default='allow', max_length=10, verbose_name='Effetto')),
                ('inherit_to_children', models.BooleanField(default=True, verbose_name='Ereditato dalle sottocartelle')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Scadenza')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='projects.projectfolder', verbose_name='Cartella')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_permission_grants', to='auth.group', verbose_name='Gruppo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_permission_grants', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Grant permesso cartella',
                'verbose_name_plural': 'Grant permessi cartella',
                'indexes': [models.Index(fields=['folder', 'permission_code'], name='projects_fo_folder__6e1e94_idx'), models.Index(fields=['user', 'permission_code'], name='projects_fo_user_id_2e518e_idx'), models.Index(fields=['group', 'permission_code'], name='projects_fo_group_i_ecae31_idx'), models.Index(fields=['expires_at'], name='projects_fo_expires_0cd7b7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('user__isnull', False)), models.Q(('group__isnull', False), ('user__isnull', True)), _connector='OR'), name='fpg_user_or_group_not_both'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('folder', 'user', 'permission_code'), name='fpg_unique_user_grant'), models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('folder', 'group', 'permission_code'), name='fpg_unique_group_grant')],
            },
        ),
    ]
