# Generated by Django 5.2.14 on 2026-06-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_root_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
