# Generated by Django 5.2.14 on 2026-06-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='revision',
            field=models.CharField(default='0', help_text='Revisione corrente del progetto. Modificabile manualmente.', max_length=32, verbose_name='Revisione'),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default='0', help_text='Versione corrente del progetto. Modificabile manualmente.', max_length=32, verbose_name='Versione'),
        ),
    ]
