# Generated by Django 5.2.14 on 2026-06-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_revision_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrevision',
            name='revision_label',
            field=models.CharField(max_length=20, verbose_name='Etichetta'),
        ),
        migrations.AlterField(
            model_name='projectrevision',
            name='revision_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero ordinamento'),
        ),
        migrations.AlterField(
            model_name='projectrevisionitem',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.projectrevision', verbose_name='Snapshot'),
        ),
    ]
