# Generated by Django 5.2.14 on 2026-05-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.projectfolder', verbose_name='Cartella progetto'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_versions', to=settings.AUTH_USER_MODEL, verbose_name='Approvato da'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.documentfile', verbose_name='File operativo'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='replaces_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='documents.documentversion', verbose_name='Sostituisce la revisione'),
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_document', to='documents.documentversion', verbose_name='Revisione corrente'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'revision_label')},
        ),
    ]
