# Generated by Django 5.2.14 on 2026-06-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_document_revision_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requires_ecn_for_revision',
            field=models.BooleanField(default=True, help_text='Se attivo, dopo la prima approvazione sarà necessario approvare un ECN prima di creare una nuova revisione.', verbose_name='Richiedi ECN per le revisioni successive'),
        ),
    ]
