# Generated by Django 5.2.14 on 2026-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_requires_approved_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allow_simple_ecn',
            field=models.BooleanField(default=True, help_text="Se disattivato, per questo documento sarà possibile creare solo ECN standard (con istruttoria e votazione CCB): l'ECN a flusso semplice (autoapprovato, senza CCB) non sarà proponibile. L'ECN standard resta sempre disponibile in ogni caso, indipendentemente da questa opzione. Il cambiamento vale solo per i prossimi ECN non ancora creati: gli ECN già esistenti e i workflow già in corso non cambiano.", verbose_name='Consenti ECN a flusso semplice per questo documento'),
        ),
    ]
