# Generated by Django 5.2.14 on 2026-05-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=50, verbose_name='Azione')),
                ('app_label', models.CharField(max_length=50, verbose_name='App')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modello')),
                ('object_id', models.CharField(max_length=50, verbose_name='ID oggetto')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Oggetto')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Modifiche')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
