# Generated by Django 5.2.14 on 2026-06-10 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identificatore univoco del lotto (es. 2026-backfill-01).', max_length=100, unique=True, verbose_name='Codice batch')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('in_progress', 'In corso'), ('completed', 'Completato'), ('rolled_back', 'Annullato')], default='draft', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_historical_batches', to=settings.AUTH_USER_MODEL, verbose_name='Completato da')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_historical_batches', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
            ],
            options={
                'verbose_name': 'Lotto sanatoria',
                'verbose_name_plural': 'Lotti sanatoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('doc_created', 'Documento creato'), ('doc_draft_created', 'Prima bozza creata'), ('doc_revision_created', 'Nuova revisione creata'), ('doc_submitted', 'Inviato in approvazione'), ('doc_approved', 'Revisione approvata'), ('doc_rejected', 'Revisione rifiutata'), ('doc_published', 'Documento pubblicato'), ('ecn_created', 'ECN creata'), ('ecn_ccb_configured', 'CCB configurata'), ('ecn_dossier_compiled', 'Dossier compilato'), ('ecn_submitted', 'ECN inviata alla CCB'), ('ecn_vote_approved', 'Voto CCB: approvato'), ('ecn_vote_rejected', 'Voto CCB: rifiutato'), ('ecn_approved', 'ECN approvata dalla CCB'), ('ecn_rejected', 'ECN rifiutata dalla CCB'), ('ecn_executed', 'ECN eseguita'), ('ecn_closed', 'ECN chiusa'), ('project_created', 'Progetto creato'), ('project_metadata_updated', 'Metadati progetto aggiornati'), ('project_version_saved', 'Versione progetto salvata'), ('project_revision_saved', 'Revisione progetto salvata'), ('project_snapshot_issued', 'Snapshot progetto emesso'), ('generic', 'Evento generico')], max_length=30, verbose_name='Tipo evento')),
                ('historical_actor_name', models.CharField(blank=True, help_text='Nome e cognome. Obbligatorio se non è collegato un utente.', max_length=200, verbose_name='Attore (nome testuale)')),
                ('historical_date', models.DateField(blank=True, help_text="Data in cui l'evento è avvenuto, secondo la fonte.", null=True, verbose_name='Data dichiarata')),
                ('date_precision', models.CharField(choices=[('exact_date', 'Data esatta'), ('month', 'Mese (giorno non noto)'), ('year', 'Anno (mese non noto)'), ('unknown', 'Data sconosciuta')], default='exact_date', max_length=20, verbose_name='Precisione data')),
                ('target_app', models.CharField(blank=True, max_length=50, verbose_name='App target')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='Modello target')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='ID oggetto')),
                ('target_repr', models.CharField(blank=True, max_length=255, verbose_name='Descrizione oggetto')),
                ('source_description', models.TextField(blank=True, help_text='Es: "Verbale riunione QM del 2021-03-15", "Timbro copia controllata n. 3".', verbose_name='Fonte')),
                ('notes', models.TextField(blank=True, verbose_name='Note aggiuntive')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrato il')),
                ('is_verified', models.BooleanField(default=False, help_text='Il responsabile qualità ha verificato la fonte.', verbose_name='Verificato')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificato il')),
                ('historical_actor_user', models.ForeignKey(blank=True, help_text="Se l'attore ha ancora un account nel sistema.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_records_as_actor', to=settings.AUTH_USER_MODEL, verbose_name='Attore (utente collegato)')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='auditlog.historicalimportbatch', verbose_name='Lotto sanatoria')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_historical_records', to=settings.AUTH_USER_MODEL, verbose_name='Registrato da')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_historical_records', to=settings.AUTH_USER_MODEL, verbose_name='Verificato da')),
            ],
            options={
                'verbose_name': 'Record storico',
                'verbose_name_plural': 'Registro storico',
                'ordering': ['historical_date', 'recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='historical_evidence/%Y/', verbose_name='File allegato')),
                ('description', models.CharField(blank=True, help_text='Es: "Verbale riunione CCB pag. 3", "Scan timbro copia controllata".', max_length=255, verbose_name='Descrizione')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Caricato il')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_historical_evidence', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da')),
                ('historical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='auditlog.historicalrecord', verbose_name='Record storico')),
            ],
            options={
                'verbose_name': 'Allegato probatorio',
                'verbose_name_plural': 'Allegati probatori',
                'ordering': ['historical_record', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='historicalrecord',
            index=models.Index(fields=['target_app', 'target_model', 'target_id'], name='auditlog_hi_target__d16287_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalrecord',
            index=models.Index(fields=['import_batch', 'event_type'], name='auditlog_hi_import__a53901_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalrecord',
            index=models.Index(fields=['historical_date'], name='auditlog_hi_histori_19929e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalrecord',
            index=models.Index(fields=['is_verified'], name='auditlog_hi_is_veri_c20bf3_idx'),
        ),
    ]
