# Generated by Django 5.2.14 on 2026-05-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='documents.documentversion', verbose_name='Revisione documento'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Richiesto da'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='approval_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalrequest', verbose_name='Richiesta'),
        ),
        migrations.AddField(
            model_name='approvalrequestapprover',
            name='approval_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='approvals.approvalrequest', verbose_name='Richiesta'),
        ),
        migrations.AddField(
            model_name='approvalrequestapprover',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Approvatore'),
        ),
        migrations.AlterUniqueTogether(
            name='approvaldecision',
            unique_together={('approval_request', 'approver')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalrequestapprover',
            unique_together={('approval_request', 'approver')},
        ),
    ]
