# Generated by Django 5.2.14 on 2026-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_approvalrequestattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldecision',
            name='snapshot_approver_display_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome approvatore (storico)'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='snapshot_approver_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ordine fase (storico)'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='snapshot_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='approval_signature_snapshots/%Y/%m/', verbose_name='Immagine firma (storico)'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='snapshot_signature_mode',
            field=models.CharField(choices=[('text_only', 'Solo testo'), ('text_and_image', 'Testo e immagine')], default='text_only', max_length=20, verbose_name='Modalità firma (storico)'),
        ),
    ]
