# Generated by Django 5.2.14 on 2026-07-27 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accounts/signatures/%Y/%m/', verbose_name='Immagine firma (PNG)')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome file originale')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dimensione (byte)')),
                ('sha256_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256')),
                ('is_active', models.BooleanField(default=True, verbose_name='Firma corrente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Firma visiva utente',
                'verbose_name_plural': 'Firme visive utente',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_signature_per_user')],
            },
        ),
    ]
