# Generated by Django 5.2.14 on 2026-05-28 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_documentversion_constraints'),
        ('projects', '0006_projectrevision_rebase_to_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codice ECN')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione modifica proposta')),
                ('motivation', models.CharField(choices=[('improvement', 'Miglioramento tecnico'), ('customer', 'Richiesta cliente'), ('non_conformity', 'Non conformità'), ('design', 'Ottimizzazione progettuale'), ('regulatory', 'Adeguamento normativo'), ('other', 'Altro')], max_length=30, verbose_name='Categoria motivazione')),
                ('motivation_detail', models.TextField(blank=True, help_text='Descrizione estesa della motivazione della variante.', verbose_name='Motivazione (dettaglio)')),
                ('commessa', models.CharField(blank=True, max_length=100, verbose_name='Commessa / ordine')),
                ('proposed_at', models.DateTimeField(auto_now_add=True, verbose_name='Proposto il')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Inviato a CCB il')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('under_review', 'In revisione CCB'), ('approved', 'Approvata'), ('rejected', 'Rifiutata'), ('closed', 'Chiusa')], default='draft', max_length=20, verbose_name='Stato')),
                ('ccb_class', models.CharField(blank=True, choices=[('class1', 'Classe 1'), ('class2', 'Classe 2')], max_length=10, null=True, verbose_name='Classe variante')),
                ('ccb_requirements', models.TextField(blank=True, help_text='Conformità ai requisiti tecnici e normativi.', verbose_name='Analisi requisiti')),
                ('ccb_technical_impact', models.TextField(blank=True, verbose_name='Impatto tecnico')),
                ('ccb_cost_impact', models.TextField(blank=True, verbose_name='Impatto costi')),
                ('ccb_time_impact', models.TextField(blank=True, verbose_name='Impatto tempi')),
                ('ccb_quality_impact', models.TextField(blank=True, verbose_name='Impatto qualità')),
                ('ccb_other_impact', models.TextField(blank=True, verbose_name='Impatto su altri documenti / parti')),
                ('ccb_notes', models.TextField(blank=True, help_text='Note aggiuntive del revisore CCB, incluse le motivazioni del rifiuto.', verbose_name='Note CCB')),
                ('ccb_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisionato il')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Eseguita il')),
                ('close_notes', models.TextField(blank=True, help_text='Note del Responsabile Qualità a chiusura della variante.', verbose_name='Note chiusura qualità')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Chiuso il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('ccb_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ecns', to=settings.AUTH_USER_MODEL, verbose_name='Revisore CCB')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_ecns', to=settings.AUTH_USER_MODEL, verbose_name='Chiuso da')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ecns', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecns', to='documents.document', verbose_name='Documento')),
                ('document_version', models.ForeignKey(help_text='Versione del documento corrente al momento della proposta.', on_delete=django.db.models.deletion.PROTECT, related_name='ecns_as_baseline', to='documents.documentversion', verbose_name='Revisione di riferimento')),
                ('executed_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecns_executed', to='documents.documentversion', verbose_name='Revisione eseguita')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecns', to='projects.project', verbose_name='Progetto')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_ecns', to=settings.AUTH_USER_MODEL, verbose_name='Proponente')),
            ],
            options={
                'verbose_name': 'ECN / Variante',
                'verbose_name_plural': 'ECN / Varianti',
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeNoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ecn/attachments/%Y/%m/', verbose_name='File')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nome file originale')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Caricato il')),
                ('size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Dimensione (byte)')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='Estensione')),
                ('change_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ecn.changenotice', verbose_name='ECN')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_ecn_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da')),
            ],
            options={
                'verbose_name': 'Allegato ECN',
                'verbose_name_plural': 'Allegati ECN',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
