# Generated by Django 5.2.14 on 2026-06-04 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0002_changenotice_ccb_policy_changenoticeapprover_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changenotice',
            name='ccb_coordinator',
            field=models.ForeignKey(blank=True, help_text="Utente incaricato di compilare il dossier istruttorio prima dell'invio ai votanti CCB.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinating_ecns', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile istruttoria CCB'),
        ),
        migrations.AlterField(
            model_name='changenotice',
            name='status',
            field=models.CharField(choices=[('draft', 'Bozza'), ('ccb_preparation', 'Istruttoria CCB'), ('under_review', 'In revisione CCB'), ('approved', 'Approvata'), ('rejected', 'Rifiutata'), ('closed', 'Chiusa')], default='draft', max_length=20, verbose_name='Stato'),
        ),
    ]
