# Generated by Django 5.2.14 on 2026-07-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0003_ccb_preparation_and_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='changenotice',
            name='flow_type',
            field=models.CharField(choices=[('standard', 'Standard (CCB)'), ('simple', 'Semplice (automatico)')], default='standard', help_text='Standard: passa da istruttoria/CCB. Semplice: autoapprovato, nessuna CCB (TASK-022).', max_length=20, verbose_name='Tipo di flusso'),
        ),
    ]
