# Generated by Django 5.2.14 on 2026-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0004_changenotice_flow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changenotice',
            name='status',
            field=models.CharField(choices=[('draft', 'Bozza'), ('ccb_preparation', 'Istruttoria CCB'), ('under_review', 'In Valutazione CCB'), ('approved', 'Approvata'), ('rejected', 'Rifiutata'), ('closed', 'Chiusa')], default='draft', max_length=20, verbose_name='Stato'),
        ),
    ]
