# Generated by Django 5.2.14 on 2026-05-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/files/%Y/%m/', verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome file originale')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='Estensione')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dimensione (byte)')),
                ('sha256_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File documento',
                'verbose_name_plural': 'File documenti',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_label', models.CharField(max_length=20, verbose_name='Etichetta revisione')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Numero revisione')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('in_approval', 'In approvazione'), ('approved', 'Approvato'), ('rejected', 'Rifiutato'), ('superseded', 'Sostituito'), ('archived', 'Archiviato')], default='draft', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Inviato in approvazione il')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approvato il')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rifiutato il')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo rifiuto')),
                ('change_summary', models.TextField(blank=True, verbose_name='Sommario modifiche')),
                ('is_current', models.BooleanField(default=False, verbose_name='È la revisione corrente')),
            ],
            options={
                'verbose_name': 'Revisione documento',
                'verbose_name_plural': 'Revisioni documento',
                'ordering': ['document', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codice')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('category', models.CharField(choices=[('QUALITY', 'Documento di qualità'), ('PROJECT', 'Documento di progetto')], max_length=20, verbose_name='Categoria')),
                ('document_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo documento')),
                ('status', models.CharField(choices=[('active', 'Attivo'), ('obsolete', 'Obsoleto'), ('archived', 'Archiviato')], default='active', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['code'],
            },
        ),
    ]
