# Generated by Django 5.2.14 on 2026-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_documentversion_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revision_scheme',
            field=models.CharField(choices=[('numeric', 'Numerica'), ('alphabetic', 'Alfabetica')], default='numeric', help_text='Schema usato per le etichette di revisione future. Non modifica lo storico.', max_length=20, verbose_name='Schema revisione'),
        ),
    ]
