# Generated by Django 5.2.14 on 2026-07-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedPDFArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/approved_pdf/%Y/%m/', verbose_name='File PDF approvato')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('generated', 'Generato'), ('failed', 'Fallito')], default='pending', max_length=20, verbose_name='Stato')),
                ('source_representation_pdf_id', models.PositiveIntegerField(blank=True, help_text='Usato per idempotenza: rigenerare non crea duplicati se la rappresentazione di origine non è cambiata.', null=True, verbose_name='ID PDF di rappresentazione di origine')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generato il')),
                ('error_message', models.TextField(blank=True, verbose_name='Messaggio di errore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF approvato',
                'verbose_name_plural': 'PDF approvati',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.approvedpdfartifact', verbose_name='PDF approvato'),
        ),
        migrations.CreateModel(
            name='RepresentationPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/representation_pdf/%Y/%m/', verbose_name='File PDF')),
                ('status', models.CharField(choices=[('not_ready', 'Non ancora pronto'), ('converting', 'Conversione in corso'), ('ready', 'Generato automaticamente'), ('confirmed', "Confermato dall'autore"), ('manual_upload_required', 'Caricamento manuale richiesto'), ('manual_uploaded', 'Caricato manualmente'), ('conversion_failed', 'Conversione fallita'), ('stale', 'Non aggiornato (sorgente modificato)')], default='not_ready', max_length=30, verbose_name='Stato')),
                ('strategy', models.CharField(blank=True, max_length=30, verbose_name='Strategia PDF')),
                ('converter', models.CharField(blank=True, max_length=30, verbose_name='Convertitore usato')),
                ('requires_confirmation', models.BooleanField(default=True, verbose_name='Richiede conferma autore')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confermato il')),
                ('source_file_hash_at_generation', models.CharField(blank=True, help_text='sha256 del DocumentFile sorgente al momento della generazione/caricamento: usato per rilevare STALE.', max_length=64, verbose_name='Hash sorgente al momento della generazione')),
                ('error_message', models.TextField(blank=True, verbose_name='Messaggio di errore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_representation_pdfs', to=settings.AUTH_USER_MODEL, verbose_name='Confermato da')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_representation_pdfs', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
            ],
            options={
                'verbose_name': 'PDF di rappresentazione',
                'verbose_name_plural': 'PDF di rappresentazione',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentversion',
            name='representation_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.representationpdf', verbose_name='PDF di rappresentazione'),
        ),
    ]
