# Generated by Django 5.2.14 on 2026-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allows_simple_ecn',
            field=models.BooleanField(default=True, help_text="Se disattivato, per questo documento non è possibile richiedere un ECN semplice (autoapprovato, senza CCB): resta disponibile solo l'ECN standard.", verbose_name='Consenti ECN semplice'),
        ),
    ]
