# Generated by Django 5.2.14 on 2026-07-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_approvedpdfartifact_documentversion_approved_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requires_approved_pdf',
            field=models.BooleanField(default=False, help_text="Se attivo: prima dell'invio in approvazione sarà richiesto un PDF che rappresenti il file sorgente (generato automaticamente quando possibile, altrimenti caricato dall'autore); al termine dell'approvazione verrà generata una copia PDF con il registro delle approvazioni e le eventuali firme visive. Le firme non costituiscono firma digitale. Il cambiamento vale solo per le prossime revisioni non ancora inviate in approvazione: le revisioni storiche e i workflow già in corso non cambiano.", verbose_name='Richiede copia PDF approvata con registro delle approvazioni'),
        ),
    ]
