# Generated by Django 5.2.14 on 2026-07-27 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_allows_simple_ecn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='kind',
            field=models.CharField(choices=[('source', 'Sorgente'), ('representation_pdf', 'PDF di rappresentazione'), ('approved_pdf', 'PDF approvato')], default='source', help_text="Sorgente = file operativo caricato dall'autore. PDF di rappresentazione = copia PDF congelata sottoposta agli approvatori. PDF approvato = artefatto generato dal sistema con il registro delle approvazioni.", max_length=30, verbose_name='Tipo file'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_for_versions', to='documents.documentfile', verbose_name='PDF approvato'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF approvato generato il'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_pdf_generation_error',
            field=models.TextField(blank=True, verbose_name='Errore generazione PDF approvato'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='approved_pdf_generation_status',
            field=models.CharField(choices=[('not_started', 'Non avviata'), ('success', 'Generato'), ('failed', 'Fallita')], default='not_started', max_length=20, verbose_name='Stato generazione PDF approvato'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='representation_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representation_for_versions', to='documents.documentfile', verbose_name='PDF di rappresentazione'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='representation_pdf_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF di rappresentazione confermato il'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='representation_pdf_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='PDF di rappresentazione confermato da'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='representation_pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF di rappresentazione generato/caricato il'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='representation_pdf_origin',
            field=models.CharField(blank=True, choices=[('native', 'Sorgente già PDF'), ('auto_converted', 'Convertito automaticamente'), ('manual_upload', 'Caricato manualmente')], max_length=20, verbose_name='Origine PDF di rappresentazione'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='representation_pdf_requires_confirmation',
            field=models.BooleanField(default=False, help_text='Vero per le conversioni automatiche a fedeltà non garantita (AUTO_UNCERTAIN).', verbose_name='Richiede conferma autore'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='representation_pdf_source_file',
            field=models.ForeignKey(blank=True, help_text='Snapshot del file sorgente da cui deriva representation_pdf. Se non coincide più con il file operativo corrente, la rappresentazione è obsoleta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentfile', verbose_name='Sorgente usato per generare il PDF di rappresentazione'),
        ),
    ]
