# Generated by Django 5.2.14 on 2026-05-28 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changenotice',
            name='ccb_policy',
            field=models.CharField(choices=[('any', 'Qualsiasi approvatore (ANY)'), ('all', 'Tutti gli approvatori (ALL)'), ('sequential', 'Sequenziale (SEQUENTIAL)')], default='all', help_text='ANY: basta un approvatore; ALL: tutti; SEQUENTIAL: in ordine.', max_length=20, verbose_name='Politica approvazione CCB'),
        ),
        migrations.CreateModel(
            name='ChangeNoticeApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Usato per la politica SEQUENTIAL.', verbose_name='Ordine')),
                ('is_required', models.BooleanField(default=True, verbose_name='Approvazione obbligatoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='ecn.changenotice', verbose_name='ECN')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecn_approver_roles', to=settings.AUTH_USER_MODEL, verbose_name='Approvatore')),
            ],
            options={
                'verbose_name': 'Approvatore CCB',
                'verbose_name_plural': 'Approvatori CCB',
                'ordering': ['order', 'id'],
                'unique_together': {('change_notice', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChangeNoticeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approvato'), ('reject', 'Rifiutato')], max_length=10, verbose_name='Decisione')),
                ('comment', models.TextField(blank=True, verbose_name='Commento')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='Deciso il')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='ecn.changenoticeapprover', verbose_name='Approvatore')),
                ('change_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='ecn.changenotice', verbose_name='ECN')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecn_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Decisione CCB',
                'verbose_name_plural': 'Decisioni CCB',
                'ordering': ['decided_at', 'id'],
                'unique_together': {('change_notice', 'approver')},
            },
        ),
    ]
