# Generated by Django 5.2.14 on 2026-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0004_changenotice_flow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='changenotice',
            name='ccb_applicability',
            field=models.TextField(blank=True, help_text='A quali unità, lotti o configurazioni si applica la modifica.', verbose_name='Applicabilità'),
        ),
        migrations.AddField(
            model_name='changenotice',
            name='ccb_constructed_impact',
            field=models.TextField(blank=True, help_text='Effetti della modifica su quanto già realizzato/installato.', verbose_name='Impatto sul costruito'),
        ),
    ]
