# Generated by Django 5.2.14 on 2026-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0005_alter_changenotice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='changenotice',
            name='applicability_category',
            field=models.CharField(blank=True, choices=[('general', 'Applicazione generale'), ('future', 'Applicazione futura'), ('limited', 'Applicazione limitata')], help_text='Ambito di applicazione della modifica. Obbligatorio per i nuovi ECN; nullo solo per ECN storici antecedenti a questa funzionalità.', max_length=20, null=True, verbose_name='Applicabilità'),
        ),
        migrations.AddField(
            model_name='changenotice',
            name='applicability_detail',
            field=models.TextField(blank=True, help_text='Obbligatorio per "Applicazione limitata": specifica progetti, commesse, configurazioni, prodotti, unità, condizioni o eccezioni interessate. Facoltativo per le altre due categorie.', verbose_name="Dettaglio dell'applicabilità"),
        ),
    ]
