# Generated by Django 5.2.14 on 2026-07-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0006_applicability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changenotice',
            name='applicability_category',
            field=models.CharField(blank=True, choices=[('general', 'Applicazione generale'), ('future', 'Applicazione futura'), ('limited', 'Applicazione limitata')], help_text="Ambito di applicazione della modifica, valutato dalla CCB nel dossier istruttorio. Nullo prima dell'istruttoria, per gli ECN a flusso semplice (nessuna CCB) e per gli ECN storici antecedenti a questa funzionalità.", max_length=20, null=True, verbose_name='Applicabilità'),
        ),
    ]
