# Generated by Django 5.2.14 on 2026-07-30 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0007_alter_changenotice_applicability_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changenotice',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='In lavorazione dal'),
        ),
        migrations.AddField(
            model_name='changenotice',
            name='locked_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Utente che sta compilando il dossier o votando in questo momento (lock temporaneo).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='locked_ecns',
                to=settings.AUTH_USER_MODEL,
                verbose_name='In lavorazione da',
            ),
        ),
    ]
