# Generated by Django 5.2.14 on 2026-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_project_version_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='version',
        ),
        migrations.AddField(
            model_name='project',
            name='revision_scheme',
            field=models.CharField(choices=[('numeric', 'Numerica'), ('alphabetic', 'Alfabetica')], default='numeric', help_text='Schema usato per la revisione corrente.', max_length=20, verbose_name='Schema revisione'),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.CharField(default='00', help_text='Revisione corrente del progetto. Modificabile manualmente.', max_length=32, verbose_name='Revisione'),
        ),
    ]
