# Generated by Django 5.2.14 on 2026-07-27 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('approvals', '0005_approvalrequestattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldecision',
            name='signature_display_name',
            field=models.CharField(blank=True, help_text='Congelato al momento della decisione (approver.get_full_name() o username).', max_length=255, verbose_name='Nome mostrato al momento della decisione'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='signature_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='accounts.usersignature', verbose_name='Firma visiva usata'),
        ),
    ]
