# Generated by Django 5.2.14 on 2026-07-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_approvalrequest_locked_at_approvalrequest_locked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldecision',
            name='signature_page',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    'Numero di pagina (1-based) dove è stata posizionata '
                    'manualmente la firma. Nullo = firma automatica in calce '
                    '(comportamento invariato).'
                ),
                null=True,
                verbose_name='Pagina firma (posizionamento libero)',
            ),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='signature_x',
            field=models.FloatField(
                blank=True,
                help_text='Coordinata X normalizzata (0.0-1.0, da sinistra) del centro della firma.',
                null=True,
                verbose_name='Posizione firma X',
            ),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='signature_y',
            field=models.FloatField(
                blank=True,
                help_text="Coordinata Y normalizzata (0.0-1.0, dall'alto) del centro della firma.",
                null=True,
                verbose_name='Posizione firma Y',
            ),
        ),
    ]
